### ISSUE TITLE
Failed to load python3 host

### ISSUE THREAD

**Issue by devrrior** [sansyrox/vim-python-virtualenv#1]
Hi, I installed the plugin and add "let g:python3_host_prog='/usr/bin/python3'" in my configuration file (init.vim). But when I use neovim, it return the following:

![image](https://user-images.githubusercontent.com/69869135/114230498-d37ae200-993e-11eb-8787-1a67a94a6d2a.png)

Neovim: 0.4.4
Python: 2.7.16

Thanks.

**Comment by sansyrox** [comment]
Hi @devrrior 👋 

Can you please share the output by running the following command in your terminal:

```
which python3
```

**Comment by devrrior** [comment]
Sure.
That return the following:

![image](https://user-images.githubusercontent.com/69869135/114242926-4bea9e80-9951-11eb-8670-699950cd78f3.png)
I suppose that directory I should add, right?

**Comment by sansyrox** [comment]
Yes, @devrrior . Now, you need to do this
```
"let g:python3_host_prog='/usr/local/bin/python3'"
```

Also, out of curiosity, how did you stumble on this repo? 😅

And please do consider starring the repo if it helps you in any way.

**Comment by devrrior** [comment]
Thank, now that's working.
I stumbled on this repo because search in google how to solve the problem with virtualenv and vim/neovim, so I found your post in dev.to.
